application: plussytodo
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: todo/images

- url: /css
  static_dir: todo/css

- url: /js
  static_dir: todo/js
  
- url: /.*
  script: _go_app